### ISSUE TITLE
roadmap to release

### ISSUE THREAD

**Issue by epogrebnyak** [epogrebnyak/rides-blueprint#27]
Critical path:

- [x] use sample data data.rar for Feb 2021 
- [x] demonstrate weekly pair partitioning
- [x] enrich output with more indicators
- [x] README editing

Enhancement:
- the lengths table filling at data import
- simlified tracks table filling at data import
- other enhancements as in https://github.com/epogrebnyak/rides-blueprint#data-pipeline
